version: '3.8'

services:
  minio:
    restart: always
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio_s3
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=bbbb2edef660739a6071ab5a4f8a869f
      - MINIO_SKIP_CLIENT=yes
      - MINIO_SERVER_URL=https://minio:9000
      - MINIO_BROWSER_REDIRECT_URL=https://localhost:9001
    extra_hosts:
      - "minio.local:192.168.0.199"
    entrypoint: 
      - sh
      - -c
      - |
        mkdir -p /root/.minio/certs
        cp /certs/public.crt /root/.minio/certs/public.crt
        cp /certs/private.key /root/.minio/certs/private.key
        exec minio server /data --console-address ':9001'
    volumes:
      - ./minio-data:/data
      - ./certs/.minio/certs:/root/.minio/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3