database:
  host: "localhost"
  port: "5432"
  username: "postgres"
  name: "S3"
  sslmode: "disable"

grpc:
  port: "50053"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  use_ssl: false
  bucket: "achievements"