database:
  host: "DB_HOST_EXAMPLE"
  port: "5432"
  username: "postgres"
  name: "S3"
  sslmode: "disable"

grpc:
  port: "50053"

minio:
  endpoint: "DB_HOST_EXAMPLE:9000"
  access_key: "ACCESS_KEY_EXAMPLE"
  secret_key: "SECRET_KEY_EXAMPLE"
  use_ssl: false
  bucket: "achievements"